# Generated by Django 3.2.20 on 2026-01-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'سترايب'), (2, 'بايبال')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'قيد المعالجه'), (1, 'مكتملة')], default=0),
        ),
    ]
